/**
 * Editable starter records for the Algorithms library.
 *
 * The store adds stable sample metadata so this module can remain focused on
 * the subject content and category structure.
 */

export const ALGORITHM_SAMPLES = [
  {
    id: "sample-algorithm-linear-search",
    category: "traditional",
    title: "Linear search",
    summary: "Inspect values in order until the target is found or the collection ends.",
    useCases: "Small or unsorted collections, linked structures, streams, and one-off searches where preprocessing would cost more than scanning.",
    invariant: "Every position before the current index has been checked and does not contain the target.",
    explanation: "Start at the first value and compare each value with the target. Return immediately on a match; if the scan reaches the end, report that the target is absent.",
    pseudocode: "for index from 0 to length - 1:\n  if values[index] == target:\n    return index\nreturn not_found",
    complexity: "Time O(n) · Space O(1)",
    visualFrames: [
      "2 7 4 9 > check 2 > continue",
      "2 7 4 9 > check 7 > continue",
      "2 7 4 9 > check 4 > found",
    ],
    tags: ["search", "array", "sequential", "beginner"],
  },
  {
    id: "sample-algorithm-binary-search",
    category: "traditional",
    title: "Binary search",
    summary: "Discard half of an ordered search space after every comparison.",
    useCases: "Finding a value or insertion point in sorted data and locating a boundary in any monotonic true/false condition.",
    invariant: "If the target or boundary exists, it remains inside the active half-open interval.",
    explanation: "Compare the middle value with the target, then retain only the half that can still contain the answer. Define the interval and equality rule precisely to avoid boundary errors.",
    pseudocode: "lo = 0; hi = length\nwhile lo < hi:\n  mid = lo + floor((hi - lo) / 2)\n  if values[mid] < target: lo = mid + 1\n  else: hi = mid\nreturn lo",
    complexity: "Time O(log n) · Space O(1) iteratively",
    visualFrames: [
      "1 3 5 7 9 11 13 > mid 7 > target 11",
      "9 11 13 > mid 11 > match",
      "index 5 > done",
    ],
    tags: ["search", "sorted data", "divide and conquer", "array"],
  },
  {
    id: "sample-algorithm-bubble-sort",
    category: "traditional",
    title: "Bubble sort",
    summary: "Swap adjacent out-of-order values until a full pass makes no changes.",
    useCases: "Teaching comparison sorting, detecting an already sorted list, and tiny inputs where clarity matters more than speed.",
    invariant: "After each complete pass, the largest unsorted value is fixed at the end of the remaining range.",
    explanation: "Walk through adjacent pairs and swap any inversion. Shorten the next pass because the largest remaining value has bubbled into place; stop early when no swap occurs.",
    pseudocode: "for end from length - 1 down to 1:\n  swapped = false\n  for i from 0 to end - 1:\n    if values[i] > values[i + 1]:\n      swap(values[i], values[i + 1]); swapped = true\n  if not swapped: break",
    complexity: "Time O(n²), best O(n) with early exit · Space O(1) · Stable",
    visualFrames: [
      "5 2 4 1 > swap 5 and 2 > 2 5 4 1",
      "2 5 4 1 > swap 5 and 4 > 2 4 5 1",
      "2 4 5 1 > swap 5 and 1 > 2 4 1 5",
    ],
    tags: ["sorting", "comparison", "in-place", "stable", "beginner"],
  },
  {
    id: "sample-algorithm-selection-sort",
    category: "traditional",
    title: "Selection sort",
    summary: "Repeatedly select the smallest remaining value and place it next.",
    useCases: "Tiny collections, teaching invariants, and environments where minimizing writes matters more than minimizing comparisons.",
    invariant: "The prefix before the current position is sorted and contains the smallest values in final order.",
    explanation: "For each output position, scan the unsorted suffix for its minimum and swap that minimum into the current position.",
    pseudocode: "for start from 0 to length - 2:\n  minimum = start\n  for i from start + 1 to length - 1:\n    if values[i] < values[minimum]: minimum = i\n  swap(values[start], values[minimum])",
    complexity: "Time O(n²) · Space O(1) · Usually not stable",
    visualFrames: [
      "5 2 4 1 > minimum 1 > swap with 5",
      "1 2 4 5 > prefix 1 fixed > scan suffix",
      "1 2 4 5 > sorted",
    ],
    tags: ["sorting", "comparison", "in-place", "beginner"],
  },
  {
    id: "sample-algorithm-insertion-sort",
    category: "traditional",
    title: "Insertion sort",
    summary: "Grow a sorted prefix by inserting each new value into its position.",
    useCases: "Small or nearly sorted inputs, online data, and the tiny partitions inside hybrid sorting implementations.",
    invariant: "Before each insertion, the prefix to the left is sorted and contains exactly the values already processed.",
    explanation: "Take the next value, shift larger prefix values one place to the right, then place the value into the gap.",
    pseudocode: "for i from 1 to length - 1:\n  value = values[i]; j = i - 1\n  while j >= 0 and values[j] > value:\n    values[j + 1] = values[j]; j -= 1\n  values[j + 1] = value",
    complexity: "Time O(n²), best O(n) · Space O(1) · Stable",
    visualFrames: [
      "2 5 | 4 1 > take 4 > shift 5",
      "2 4 5 | 1 > prefix grows",
      "1 2 4 5 > sorted",
    ],
    tags: ["sorting", "comparison", "in-place", "stable", "nearly sorted"],
  },
  {
    id: "sample-algorithm-merge-sort",
    category: "traditional",
    title: "Merge sort",
    summary: "Split the input, sort each half, and merge two ordered sequences.",
    useCases: "Stable general sorting, linked lists, external sorting, and data too large to sort as one in-memory block.",
    invariant: "During merge, the output contains the smallest consumed values in sorted order; both remaining inputs stay sorted.",
    explanation: "Recursively divide until every run has one value. Merge two runs by repeatedly taking the smaller front value, then append the remainder.",
    pseudocode: "sort(values):\n  if length <= 1: return values\n  mid = floor(length / 2)\n  left = sort(values[0:mid]); right = sort(values[mid:])\n  return merge(left, right)",
    complexity: "Time O(n log n) · Space O(n) for arrays · Stable",
    visualFrames: [
      "5 2 4 1 > split > 5 2 | 4 1",
      "5 | 2 | 4 | 1 > merge pairs > 2 5 | 1 4",
      "2 5 | 1 4 > merge > 1 2 4 5",
    ],
    tags: ["sorting", "divide and conquer", "stable", "recursion"],
  },
  {
    id: "sample-algorithm-quicksort",
    category: "traditional",
    title: "Quicksort",
    summary: "Partition values around a pivot, then sort the two resulting sides.",
    useCases: "Fast in-memory comparison sorting when average performance and cache locality matter and stability is not required.",
    invariant: "After partitioning, values on one side satisfy the lower relation to the pivot and values on the other satisfy the upper relation.",
    explanation: "Choose a pivot, partition the active range around it, then recursively sort the smaller ranges. Pivot strategy and duplicate handling determine practical performance.",
    pseudocode: "quicksort(lo, hi):\n  if lo >= hi: return\n  pivot_index = partition(values, lo, hi)\n  quicksort(lo, pivot_index - 1)\n  quicksort(pivot_index + 1, hi)",
    complexity: "Average O(n log n), worst O(n²) · Stack O(log n) average · Unstable",
    visualFrames: [
      "5 2 4 1 > pivot 4 > partition",
      "2 1 | 4 | 5 > sort left and right",
      "1 2 4 5 > sorted",
    ],
    tags: ["sorting", "divide and conquer", "partition", "in-place"],
  },
  {
    id: "sample-algorithm-heap-sort",
    category: "traditional",
    title: "Heap sort",
    summary: "Build a max-heap, then repeatedly move its maximum to the final position.",
    useCases: "Guaranteed O(n log n) in-place sorting and systems where predictable worst-case time matters more than stability.",
    invariant: "The suffix is in final sorted order, while the prefix remains a valid max-heap.",
    explanation: "Heapify the array so the root is largest. Swap the root with the end of the active heap, shrink the heap, and sift the new root down.",
    pseudocode: "build_max_heap(values)\nfor end from length - 1 down to 1:\n  swap(values[0], values[end])\n  sift_down(values, 0, end)",
    complexity: "Time O(n log n) · Space O(1) · Unstable",
    visualFrames: [
      "2 5 4 1 > heapify > 5 2 4 1",
      "5 2 4 1 > move max > 1 2 4 | 5",
      "heapify prefix > 4 2 1 | 5 > repeat",
    ],
    tags: ["sorting", "heap", "in-place", "priority"],
  },
  {
    id: "sample-algorithm-breadth-first-search",
    category: "traditional",
    title: "Breadth-first search",
    summary: "Explore a graph one distance layer at a time using a queue.",
    useCases: "Shortest paths in unweighted graphs, degrees of separation, flood fill, and level-order tree traversal.",
    invariant: "When a node leaves the queue, its recorded distance is the shortest number of edges from the start.",
    explanation: "Mark the start visited and enqueue it. Remove the oldest node, then mark and enqueue each unseen neighbor so no node enters twice.",
    pseudocode: "queue = [start]; visited = {start}\nwhile queue not empty:\n  node = queue.pop_front()\n  for neighbor in graph[node]:\n    if neighbor not in visited:\n      visited.add(neighbor)\n      queue.push_back(neighbor)",
    complexity: "Time O(V + E) · Space O(V)",
    visualFrames: [
      "A > frontier B C",
      "B C > frontier D E",
      "D E > goal E found",
    ],
    tags: ["graph", "search", "queue", "shortest path", "traversal"],
  },
  {
    id: "sample-algorithm-depth-first-search",
    category: "traditional",
    title: "Depth-first search",
    summary: "Follow one branch as far as possible before backtracking.",
    useCases: "Connectivity, cycle detection, maze exploration, component labeling, dependency analysis, and tree traversal.",
    invariant: "Every visited node has a complete path from the start; a finished node has no unexplored outgoing edge.",
    explanation: "Mark a node visited, then recursively visit each unseen neighbor. An explicit stack provides the same depth-first order without recursive call-stack limits.",
    pseudocode: "visit(node):\n  visited.add(node)\n  for neighbor in graph[node]:\n    if neighbor not in visited:\n      visit(neighbor)",
    complexity: "Time O(V + E) · Space O(V)",
    visualFrames: [
      "A > visit B > visit D",
      "D > backtrack B > visit E",
      "E > backtrack A > visit C",
    ],
    tags: ["graph", "search", "stack", "recursion", "traversal"],
  },
  {
    id: "sample-algorithm-tree-traversals",
    category: "traditional",
    title: "Binary tree traversals",
    summary: "Visit a tree in preorder, inorder, or postorder according to when the root is processed.",
    useCases: "Serializing trees, reading binary-search-tree values in order, evaluating expression trees, and deleting subtrees safely.",
    invariant: "Each recursive call processes exactly the nodes in its subtree once, in the traversal's defined root/left/right order.",
    explanation: "Preorder handles the root before children, inorder between the left and right child, and postorder after both children. The recursion shape stays the same; only the visit point moves.",
    pseudocode: "traverse(node):\n  if node is null: return\n  traverse(node.left)\n  visit(node)  // inorder\n  traverse(node.right)",
    complexity: "Time O(n) · Space O(h), where h is tree height",
    visualFrames: [
      "root 4 > left 2 > left 1",
      "visit 1 > visit 2 > visit 3",
      "visit 4 > visit 5 6 7",
    ],
    tags: ["tree", "traversal", "recursion", "stack"],
  },
  {
    id: "sample-algorithm-dijkstra",
    category: "traditional",
    title: "Dijkstra's shortest path",
    summary: "Expand the unsettled vertex with the smallest known distance.",
    useCases: "Shortest routes in graphs whose edge weights are all non-negative, including road networks and network latency.",
    invariant: "When a vertex is removed from the min-priority queue at its best distance, that distance is final.",
    explanation: "Store the start at distance zero. Repeatedly take the nearest unsettled vertex and relax its outgoing edges, updating any neighbor reached more cheaply.",
    pseudocode: "distance[start] = 0; queue.push(0, start)\nwhile queue not empty:\n  cost, node = queue.pop_min()\n  if cost != distance[node]: continue\n  for neighbor, weight in graph[node]:\n    if cost + weight < distance[neighbor]:\n      update distance and push neighbor",
    complexity: "Time O((V + E) log V) with a binary heap · Space O(V + E)",
    visualFrames: [
      "A 0 > relax B 4 and C 2",
      "C 2 > improve B to 3 and set D 7",
      "B 3 > improve D to 6 > shortest settled",
    ],
    tags: ["graph", "shortest path", "greedy", "priority queue", "weighted"],
  },
  {
    id: "sample-algorithm-topological-sort",
    category: "traditional",
    title: "Topological sort",
    summary: "Order a directed acyclic graph so every dependency appears before its dependents.",
    useCases: "Build systems, course prerequisites, job scheduling, spreadsheet dependencies, and migration ordering.",
    invariant: "Every emitted vertex currently has zero incoming edges from vertices that have not yet been emitted.",
    explanation: "Count incoming edges, queue every zero-indegree vertex, then emit one and remove its outgoing edges. If fewer than all vertices are emitted, the graph contains a cycle.",
    pseudocode: "queue = all nodes with indegree 0\nwhile queue not empty:\n  node = queue.pop_front(); output.append(node)\n  for neighbor in graph[node]:\n    indegree[neighbor] -= 1\n    if indegree[neighbor] == 0: queue.push_back(neighbor)\nif output size < V: cycle",
    complexity: "Time O(V + E) · Space O(V)",
    visualFrames: [
      "plan > zero indegree A B",
      "emit A > C still blocked",
      "emit B > C unlocked > emit C",
    ],
    tags: ["graph", "dependency", "dag", "queue", "ordering"],
  },
  {
    id: "sample-algorithm-two-pointers",
    category: "traditional",
    title: "Two pointers",
    summary: "Move two indices through a sequence while preserving a useful relationship between them.",
    useCases: "Pair sums in sorted arrays, deduplication, partitioning, palindrome checks, and merging ordered sequences.",
    invariant: "Everything outside the active pointer range has already been ruled out or placed correctly.",
    explanation: "Place pointers at positions that match the problem shape—often opposite ends. Compare the current state and move only the pointer whose movement can improve it.",
    pseudocode: "left = 0; right = length - 1\nwhile left < right:\n  total = values[left] + values[right]\n  if total == target: return pair\n  if total < target: left += 1\n  else: right -= 1",
    complexity: "Time O(n) · Space O(1), after sorting when required",
    visualFrames: [
      "1 2 4 7 11 > left 1 + right 11 = 12",
      "sum high > move right > 1 + 7 = 8",
      "sum low > move left > 2 + 7 = 9 found",
    ],
    tags: ["array", "sequence", "search", "in-place", "pattern"],
  },
  {
    id: "sample-algorithm-sliding-window",
    category: "traditional",
    title: "Sliding window",
    summary: "Maintain an answer for a contiguous range as its boundaries move.",
    useCases: "Longest or shortest qualifying substring, fixed-size rolling statistics, rate limits, and contiguous subarray constraints.",
    invariant: "The current window's stored summary exactly represents the values between left and right.",
    explanation: "Extend the right boundary and update the window state. When the constraint fails, move the left boundary and remove its contribution until the window is valid again.",
    pseudocode: "left = 0\nfor right from 0 to length - 1:\n  add(values[right])\n  while window invalid:\n    remove(values[left]); left += 1\n  answer = best(answer, right - left + 1)",
    complexity: "Usually time O(n) · Auxiliary space depends on window state",
    visualFrames: [
      "A B C A > grow to A B C > valid",
      "add A > duplicate A > shrink left",
      "B C A > valid length 3",
    ],
    tags: ["array", "string", "sequence", "window", "pattern"],
  },
  {
    id: "sample-algorithm-prefix-sums",
    category: "traditional",
    title: "Prefix sums",
    summary: "Precompute cumulative totals so range sums become constant-time subtraction.",
    useCases: "Repeated interval totals, cumulative counts, subarray equations, image-area sums, and difference-array techniques.",
    invariant: "prefix[i] equals the total of all input values before index i.",
    explanation: "Build a prefix array with an initial zero. The total over a half-open range [left, right) is prefix[right] minus prefix[left].",
    pseudocode: "prefix[0] = 0\nfor i from 0 to length - 1:\n  prefix[i + 1] = prefix[i] + values[i]\nrange_sum(left, right) = prefix[right] - prefix[left]",
    complexity: "Build O(n) · Query O(1) · Space O(n)",
    visualFrames: [
      "values 2 5 1 4 > prefix 0 2 7 8 12",
      "range 1 to 3 > prefix 4 minus prefix 1",
      "12 minus 2 > 10",
    ],
    tags: ["array", "range query", "preprocessing", "math", "pattern"],
  },
  {
    id: "sample-algorithm-euclidean-gcd",
    category: "traditional",
    title: "Euclidean greatest common divisor",
    summary: "Replace a pair of integers with the smaller value and the remainder.",
    useCases: "Reducing fractions, modular arithmetic, ratio normalization, and number-theory utilities.",
    invariant: "gcd(a, b) is unchanged when the pair becomes (b, a mod b).",
    explanation: "Repeatedly divide and keep the remainder. When the remainder reaches zero, the remaining non-zero value is the greatest common divisor.",
    pseudocode: "while b != 0:\n  a, b = b, a mod b\nreturn abs(a)",
    complexity: "Time O(log min(a, b)) · Space O(1)",
    visualFrames: [
      "gcd 48 18 > 48 mod 18 = 12",
      "18 12 > remainder 6",
      "12 6 > remainder 0 > gcd 6",
    ],
    tags: ["math", "number theory", "iterative", "beginner"],
  },
  {
    id: "sample-algorithm-a-star",
    category: "advanced",
    title: "A* search",
    summary: "Guide shortest-path search with an estimate of the remaining cost.",
    useCases: "Game navigation, robotics, route finding, and state-space search with an informative admissible heuristic.",
    invariant: "The priority of a frontier state is its known start cost plus its estimated remaining cost; with a consistent heuristic, closed states need not reopen.",
    explanation: "A* relaxes edges like Dijkstra but orders the frontier by f = g + h. The heuristic focuses work toward the goal without sacrificing optimality when it never overestimates.",
    pseudocode: "g[start] = 0; open.push(h(start), start)\nwhile open not empty:\n  node = open.pop_min()\n  if node == goal: reconstruct path\n  for neighbor, cost in edges(node):\n    candidate = g[node] + cost\n    if candidate < g[neighbor]:\n      update parent and g\n      open.push(candidate + h(neighbor), neighbor)",
    complexity: "Worst-case exponential · Common graph implementation O((V + E) log V) · Space O(V)",
    visualFrames: [
      "start > score g 0 + h 6",
      "frontier east 5 | north 8 > choose east",
      "east > update goal score 7 > reconstruct",
    ],
    tags: ["graph", "shortest path", "heuristic", "priority queue", "pathfinding"],
  },
  {
    id: "sample-algorithm-union-find",
    category: "advanced",
    title: "Union–find",
    summary: "Track disjoint groups with parent links, path compression, and union by rank.",
    useCases: "Dynamic connectivity, Kruskal's minimum spanning tree, clustering, account merging, and cycle detection.",
    invariant: "Every member of a set reaches the same representative root; union changes roots without splitting an existing set.",
    explanation: "Find follows parent links to a representative and compresses the path. Union attaches the shallower representative below the deeper one so future finds remain nearly constant-time.",
    pseudocode: "find(x):\n  if parent[x] != x: parent[x] = find(parent[x])\n  return parent[x]\nunion(a, b):\n  ra = find(a); rb = find(b)\n  if ra == rb: return\n  attach lower-rank root below higher-rank root",
    complexity: "Amortized O(α(n)) per operation · Space O(n)",
    visualFrames: [
      "A B | C D > union A B",
      "A-B | C-D > union B C",
      "A-B-C-D > find D compresses to root A",
    ],
    tags: ["graph", "disjoint set", "connectivity", "amortized", "data structure"],
  },
  {
    id: "sample-algorithm-kmp",
    category: "advanced",
    title: "Knuth–Morris–Pratt string search",
    summary: "Reuse matched-prefix information instead of restarting after a mismatch.",
    useCases: "Exact substring search, streaming pattern matching, and repeated searches with a fixed pattern.",
    invariant: "Before comparing the next characters, the pattern prefix of length j matches the suffix ending immediately before the current text position.",
    explanation: "Precompute the longest proper prefix that is also a suffix for every pattern position. On mismatch, jump j to the next viable border instead of moving the text index backward.",
    pseudocode: "lps = build_prefix_table(pattern)\nj = 0\nfor i from 0 to text.length - 1:\n  while j > 0 and text[i] != pattern[j]: j = lps[j - 1]\n  if text[i] == pattern[j]: j += 1\n  if j == pattern.length: return i - j + 1",
    complexity: "Preprocess O(m) · Search O(n) · Space O(m)",
    visualFrames: [
      "text ABABAC > pattern ABAC > match ABA",
      "mismatch B vs C > border A retained",
      "resume at text A > pattern found",
    ],
    tags: ["string", "search", "prefix", "pattern matching"],
  },
  {
    id: "sample-algorithm-longest-common-subsequence",
    category: "advanced",
    title: "Longest common subsequence",
    summary: "Use dynamic programming to preserve the longest ordered sequence shared by two inputs.",
    useCases: "Diff tools, version comparison, sequence similarity, and introducing two-dimensional dynamic programming.",
    invariant: "dp[i][j] is the optimal subsequence length for the first i values of one sequence and first j values of the other.",
    explanation: "Matching final values extend the best result from both shorter prefixes. A mismatch takes the better result obtained by dropping one final value or the other.",
    pseudocode: "for i from 1 to a.length:\n  for j from 1 to b.length:\n    if a[i - 1] == b[j - 1]:\n      dp[i][j] = dp[i - 1][j - 1] + 1\n    else:\n      dp[i][j] = max(dp[i - 1][j], dp[i][j - 1])",
    complexity: "Time O(nm) · Space O(nm), reducible to O(min(n, m)) for length only",
    visualFrames: [
      "ABC | AEC > A matches > length 1",
      "B vs E > carry best 1",
      "C matches C > length 2 > subsequence AC",
    ],
    tags: ["dynamic programming", "sequence", "string", "optimization", "table"],
  },
  {
    id: "sample-algorithm-bellman-ford",
    category: "advanced",
    title: "Bellman–Ford shortest paths",
    summary: "Relax every edge repeatedly to handle negative weights and expose negative cycles.",
    useCases: "Shortest paths with negative edges, currency-arbitrage models, routing protocols, and detecting reachable negative cycles.",
    invariant: "After pass k, every shortest path using at most k edges has its correct distance.",
    explanation: "Initialize the start at zero, then relax all edges V−1 times. A further successful relaxation proves a reachable negative cycle, because a simple shortest path cannot need V edges.",
    pseudocode: "distance[start] = 0\nrepeat V - 1 times:\n  changed = false\n  for (u, v, weight) in edges:\n    if distance[u] + weight < distance[v]:\n      distance[v] = distance[u] + weight; changed = true\n  if not changed: break\nif any edge can still relax: negative cycle",
    complexity: "Time O(VE) · Space O(V)",
    visualFrames: [
      "pass 1 > A 0 > B 4 > C 7",
      "pass 2 > C improves through B to -1",
      "extra pass improves again > negative cycle detected",
    ],
    tags: ["graph", "shortest path", "negative weight", "dynamic programming"],
  },
];
